<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: cmerchant
 * Date: Mon, 10 Dec 2018 20:08:31 +0000
 */

$conf['title'] = 'Christopher\'s Knowledgebase';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register,profile';

// end auto-generated content
